--
--  Author: Fabian Rostello
--  Date: 08.10.2026
--  File: add_profiles.sql
--  Description: Several profiles per reader, each with its interests, its sources, its briefings and
--               the terms it follows; the cards a briefing was asked for
--
-- A reader may follow two worlds that have nothing in common ("Travail", "Loisirs"): one profile mixed
-- them in one briefing and one list of sources. Each profile is now independent: its text, interests,
-- refusals, the sources found for it or added by hand, its trusted sources, its briefings and thumbs.
--
-- Run in three parts, in order. A and B add and fill, and leave the server of today working. C swaps the
-- keys: run it right before deploying the server that uses them (bash deploy/deploy.sh), the server of
-- before can't save a profile once it ran.

-- ===== A. Add (nothing removed) =====

-- a profile has its own id, a name, and the terms it follows (names or words: a news naming one is
-- always shown, in a section of the briefing of its own)
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS name text NOT NULL DEFAULT 'Profil';
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS watch_terms text[] NOT NULL DEFAULT '{}';
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS u_user_profiles_id ON public.user_profiles (id);

-- what belongs to a profile
ALTER TABLE public.profile_interests ADD COLUMN IF NOT EXISTS id_profile integer;
ALTER TABLE public.user_feeds ADD COLUMN IF NOT EXISTS id_profile integer;
ALTER TABLE public.briefings ADD COLUMN IF NOT EXISTS id_profile integer;
CREATE INDEX IF NOT EXISTS i_profile_interests_profile ON public.profile_interests (id_profile);
CREATE INDEX IF NOT EXISTS i_user_feeds_profile ON public.user_feeds (id_profile);
CREATE INDEX IF NOT EXISTS i_briefings_profile ON public.briefings (id_profile, created_at DESC);
CREATE INDEX IF NOT EXISTS i_user_profiles_user ON public.user_profiles (id_user);
-- a source is added once per profile (the one per reader goes in C). Rows without a profile yet never
-- meet: two NULL are not equal
CREATE UNIQUE INDEX IF NOT EXISTS u_user_feeds_profile ON public.user_feeds (id_profile, url);

-- the cards asked for (10, 20 or 30), and the news of the terms the profile follows:
-- [{term, news: [{storyId, title, url, source, language, publishedAt, media}]}]
ALTER TABLE public.briefings ADD COLUMN IF NOT EXISTS size integer NOT NULL DEFAULT 10;
ALTER TABLE public.briefings ADD COLUMN IF NOT EXISTS watched jsonb;

-- rank_stories by the interests of one profile (rank_stories reads all the interests of a user, kept
-- for the server of before until C ran)
CREATE OR REPLACE FUNCTION public.rank_profile_stories(profile_id integer, feed_urls text[], languages text[], since timestamptz,
                                                       sparse_weight real, excluded integer[], max_stories integer)
    RETURNS TABLE (id_story integer, id_article integer, id_interest integer, score double precision)
    LANGUAGE sql
    STABLE
AS $$
    WITH visible AS (
        -- a news in several feeds of the user is scored once
        SELECT DISTINCT ON (a.link) a.id, a.id_story, a.text_dense, a.text_sparse
        FROM articles a
        JOIN feeds f ON f.id = a.id_feed
        WHERE f.url = ANY(feed_urls)
          AND (languages IS NULL OR a.lang = ANY(languages))   -- NULL: every language, translated for the reader
          AND a.embedded_at IS NOT NULL
          AND a.id_story IS NOT NULL
          AND a.id_story <> ALL(COALESCE(excluded, '{}'))
          AND COALESCE(a.published_at, a.created_at) >= since
        ORDER BY a.link, COALESCE(a.published_at, a.created_at) DESC
    ), scored AS (
        SELECT v.id, v.id_story, best.id AS id_interest, best.score
        FROM visible v
        CROSS JOIN LATERAL (
            SELECT i.id, i.weight * (-(v.text_dense <#> i.dense) - sparse_weight * (v.text_sparse <#> i.sparse)) AS score
            FROM profile_interests i
            WHERE i.id_profile = profile_id AND i.dense IS NOT NULL
            ORDER BY 2 DESC
            LIMIT 1
        ) best
    )
    SELECT s.id_story, s.id, s.id_interest, s.score
    FROM (SELECT DISTINCT ON (id_story) id_story, id, id_interest, score FROM scored ORDER BY id_story, score DESC) s
    ORDER BY s.score DESC
    LIMIT max_stories
$$;

-- ===== B. Fill: what a reader had goes to their one profile =====
-- (run again after the deploy if the server of before saved rows in between: it only fills what is empty)

UPDATE public.profile_interests i SET id_profile = p.id
FROM public.user_profiles p WHERE p.id_user = i.id_user AND i.id_profile IS NULL;
UPDATE public.user_feeds uf SET id_profile = p.id
FROM public.user_profiles p WHERE p.id_user = uf.id_user AND uf.id_profile IS NULL;
UPDATE public.briefings b SET id_profile = p.id
FROM public.user_profiles p WHERE p.id_user = b.id_user AND b.id_profile IS NULL;

-- ===== C. Swap the keys (right before the deploy) =====

BEGIN;
-- a reader has several profiles: the key is the profile
ALTER TABLE public.user_profiles DROP CONSTRAINT IF EXISTS user_profiles_pkey;
ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY USING INDEX u_user_profiles_id;

-- deleting a profile deletes its interests, sources and briefings, as deleting a reader does
ALTER TABLE public.profile_interests ADD CONSTRAINT fk_profile_interests_profile
    FOREIGN KEY (id_profile) REFERENCES public.user_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.user_feeds ADD CONSTRAINT fk_user_feeds_profile
    FOREIGN KEY (id_profile) REFERENCES public.user_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.briefings ADD CONSTRAINT fk_briefings_profile
    FOREIGN KEY (id_profile) REFERENCES public.user_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profile_interests ALTER COLUMN id_profile SET NOT NULL;
ALTER TABLE public.briefings ALTER COLUMN id_profile SET NOT NULL;

-- a source may be in two profiles of one reader (once per profile: u_user_feeds_profile). The sources
-- of a reader who never wrote a profile have none: they stay, without a profile, until one is written
ALTER TABLE public.user_feeds DROP CONSTRAINT IF EXISTS u_user_feeds;
COMMIT;
