@startuml

title Class Diagram - Backend

left to right direction

package "Presentation Layer" {
    class router
    class newsRouter
    class loginRouter
    class historyRouter
    class newsController
    class loginController
    class historyController
}

package "Business Layer" {
    class newsService
    class loginService
    class historyService
    class loginModel
    class historyModel
    class links
    class scraper
    class filter
    class jwt
    class pwdHasher
}

package "Infrastructure Layer" {
    class "Input/Output" as io
    class BasicCrawler
    class CheerioCrawler
    class JasonWebToken
    class bcrypt
}

EndUser --> router
router --> newsRouter
router --> loginRouter
router --> historyRouter
newsRouter <--> newsController
loginRouter <--> loginController
historyRouter <--> historyController

newsController <--> newsService
newsService <--> links
newsService <--> scraper
newsService <--> filter
loginController <--> loginService
loginService <--> loginModel
loginService --> pwdHasher
loginService --> jwt
jwt <--> JasonWebToken
pwdHasher <--> bcrypt
historyController <--> historyService
historyService <--> historyModel

links <--> io
scraper <--> BasicCrawler
scraper <--> CheerioCrawler

@enduml