@startuml
title Suppression de la recherche personnalisée (Backend)
autonumber

participant "Client (App)" as Client
participant "Router" as Router
participant "Controller" as Controller
participant "Service" as Service
participant "Model" as Model
database "Storage (DB)" as Storage


Client -> Router : DELETE /customsearch (search_id)
Router -> Controller : processRequest(search_id)
Controller -> Service : deleteUserCustomSearch(search_id)
Service -> Model : deleteUserCustomSearch(search_id)
Model -> Storage : DELETE custom_searches
Storage --> Model : confirm_success
Model --> Service : confirm_success
Service --> Controller : confirm_success
Controller --> Router : HTTP 200
Router --> Client : Response JSON (confirmation)

@enduml